### ISSUE TITLE
can not open file 'nvinfer.lib'

### ISSUE THREAD

**Issue by Blaise-wig** [agrechnev/trt-cpp-min#1]
Hello,
Firstly,  I appreciate the work you did.
After trying to compile your codes with  CMake, I got the error (can not open file 'nvinfer.lib'). I have all the cuda packages installed already. What might be the issue?

**Comment by Blaise-wig** [comment]
### I also get this warning

Warning	C26451	Arithmetic overflow: Using operator '*' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '*' to avoid overflow (io.2).	

I will be glad if you can help.

**Comment by agrechnev** [comment]
"I have all the cuda packages installed'" 
But do you have tensorrt itself installed? Never saw such error messages, sorry. The code works fine in docker, just checked (nvcr.io/nvidia/tensorrt:21.03-py3 to be precise). Installing TensorRT without docker is not easy.

**Comment by Blaise-wig** [comment]
Yes tensorrt is installed.
The issue is, this line _link_libraries(nvinfer_ nvonnxparser ${CUDA_LIBRARIES})
does not locate the nvinfer.lib and nvonnxpaser.lib but it instead locate cudart.static.lib.
I don't know why

**Comment by Blaise-wig** [comment]
Is there a way can link the libraries directly from the path on my computer?

**Comment by agrechnev** [comment]
You can always play around with the CMake project, see numerous docs and forums online.
Try things like:
link_directories
find_library
imported libraries

**Comment by Blaise-wig** [comment]
Thank you!
